### ISSUE TITLE
运行以后对话报错如下

### ISSUE THREAD

**Issue by realzsy** [slippersheepig/bard-web#2]
Google Bard encountered an error: b')]}'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n55\n[["di",98],["af.httprm",98,"-7993066979526883887",3]]\n25\n[["e",4,null,null,130]]\n'.

**Comment by slippersheepig** [comment]
刚更新了一下cookie测试，正常使用。不过目前__Secure-1PSIDTS这个值很容易就过期，暂时没有办法解决

看看是不是cookie值复制错了

**Comment by cj1357** [comment]
我这边是没问题的

**Comment by slippersheepig** [comment]
[acheong08](https://github.com/acheong08/Bard)貌似弃坑了，先archive
